### ISSUE TITLE
Unity 2019 Support

### ISSUE THREAD

**Issue by ToadsworthLP** [rygo6/GTLogicGraph#2]
Since UIElements moved out of the experimental phase in Unity 2019 and is now essentially production-ready, it would be great if this library worked in the most recent Unity release. I already tried fixing it myself, but it seems to involve more than just replacing all using directives to point to the now non-experimental UIElements library.
Thank you in advance!

**Comment by rygo6** [comment]
Oh great to hear it's out of experimental. I will update my project to 2019 this weekend and work on that.

**Comment by mert-dev-acc** [comment]
Is there any news ?

**Comment by rygo6** [comment]
Detour through life and work. I'll be able to get back to this next week.

**Comment by m3rt32** [comment]
Cool! Btw, one additional thing, I am unable to find where to create a new graph asset. There is no menu item. Am I missing something?

**Comment by ToadsworthLP** [comment]
There has been some activity on the repo, especially #78aa3eb827cdf18951f7fd64f57088f4733f166e looked very promising, but it seems like the contents of the GeoTetra.GTLogicGraph.Extensions namespace are not on this repository. I assume that this is not the intended behaviour as it essentially prevents use of this library, and because this first occured after the Unity 2019 compatibility was introduced, it seemed appropriate to report it here instead of in a new issue.

**Comment by rygo6** [comment]
Ya I updated it in 2019 and fixed all the compiler errors. Seems to be fine so far. 

I still wouldn't recommend using this for anything serious yet. Now that it is out of the experimental namespace I am going to try and get this to some level of complete. Probably change quite a bit in the process.

**Comment by mert-dev-acc** [comment]
Cool, thank you!
